{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dxprotocol\/dxerror\/sealedsenderselfsend(_:)"]}],"abstract":[{"type":"text","text":"The sender tried to send a message to itself using a sealed sender key."}],"kind":"symbol","identifier":{"url":"doc:\/\/DXProtocol\/documentation\/DXProtocol\/DXError\/sealedSenderSelfSend(_:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","roleHeading":"Case","externalID":"s:10DXProtocol7DXErrorO20sealedSenderSelfSendyACSScACmF","title":"DXError.sealedSenderSelfSend(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sealedSenderSelfSend"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"DXProtocol"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sealedSenderSelfSend"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DXProtocol\/documentation\/DXProtocol","doc:\/\/DXProtocol\/documentation\/DXProtocol\/DXError"]]},"references":{"doc://DXProtocol/documentation/DXProtocol":{"type":"topic","kind":"symbol","url":"\/documentation\/dxprotocol","role":"collection","abstract":[],"identifier":"doc:\/\/DXProtocol\/documentation\/DXProtocol","title":"DXProtocol"},"doc://DXProtocol/documentation/DXProtocol/DXError":{"title":"DXError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DXError","kind":"identifier"}],"type":"topic","url":"\/documentation\/dxprotocol\/dxerror","kind":"symbol","abstract":[{"type":"text","text":"An enum that represents errors that can occur in the DataX Cryptography library."}],"role":"symbol","identifier":"doc:\/\/DXProtocol\/documentation\/DXProtocol\/DXError","navigatorTitle":[{"kind":"identifier","text":"DXError"}]},"doc://DXProtocol/documentation/DXProtocol/DXError/sealedSenderSelfSend(_:)":{"kind":"symbol","identifier":"doc:\/\/DXProtocol\/documentation\/DXProtocol\/DXError\/sealedSenderSelfSend(_:)","role":"symbol","url":"\/documentation\/dxprotocol\/dxerror\/sealedsenderselfsend(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sealedSenderSelfSend"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The sender tried to send a message to itself using a sealed sender key."}],"title":"DXError.sealedSenderSelfSend(_:)","type":"topic"}}}